# Generated by Django 4.0 on 2022-11-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
