# Generated by Django 4.0 on 2022-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0002_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
